config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tracks#index'
  resources :tracks, only: :show
  post :search, to: "tracks#search", as: 'search_track'
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :url, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :tracks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tracks_controller.rb
require 'open-uri'
require 'nokogiri'

class TracksController < ApplicationController
  def index
    if params[:id]
      @tracks = Track.where(id: params[:id])
    else
      @tracks = Track.all
    end
  end

  def search
    @tracks = []
    search_query = params[:search_query]
    url = "https://www.youtube.com/results?search_query=#{search_query}"
    html_file = open(url)
    html_doc = Nokogiri::HTML(html_file)
    html_doc.search('.yt-lockup-title a').each do |result|
      track_url = "https://www.youtube.com" + result.attribute('href').value
      track_name = result.text
      track_picture = result.parent.parent.previous.search('img').first.attribute('src').value
      track_picture = "https:" + track_picture unless track_picture.starts_with?('https:')
      track = Track.find_or_create_by(url: track_url, name: track_name, picture: track_picture)
      @tracks << track
    end
    redirect_to(root_path(id: @tracks.map{ |track| track.id }))
  end

  def show
    @track = Track.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="">
      <%= image_tag "logo.png" %>
    </a>

    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search for featured stuff">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    <hr>
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>

app/views/tracks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="search">
        <%= form_tag search_track_path do %>
          <%= text_field_tag :search_query, nil, class: "form-control", placeholder: "Search for music" %>
        <% end %>
      </div>
      <%= react_component "TrackList",
        render(template: 'tracks/index.json.jbuilder'),
        prerender: false %>
    </div>
  </div>
</div>

app/views/tracks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <iframe class="" src="http://www.vidtomp3.com/?url=<%= @track.url %>" width="1000" height="1000" />
    </div>
  </div>
</div>